server:
  port: 8128
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study-idea?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.200.10
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
  security:
    user:
       name: admin
       password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
project:
  jwt:
    header: Authorization
    expire: 604800
    secret: 8d2a19e9-2fd2dd43-6d4b7f9ea9786b



#
#spring.datasource.url=jdbc:mysql://localhost:3306/study-idea?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#
#mybatis.mapper-locations=classpath:/mapper/*.xml
#mybatis.type-aliases-package=com.end.project.dao
#
#
## REDIS (Redis 配置)
## 连接工厂使用的数据库索引
#spring.redis.database= 0
## Redis服务器主机
#spring.redis.host=192.168.200.10
## redis服务器端口
#spring.redis.port= 6379
## 登录redis服务器的密码
#spring.redis.password=
## 给定时间池可以分配的最大连接数 使用负值为无限制
#spring.redis.pool.max-active= 8
## 连接分配在池耗尽之前在抛出异常之前应阻止的最大时间量（连接池最大阻塞等待时间以毫秒为单位） 使用负值无限期地阻止
#spring.redis.pool.max-wait= -1
## 连接池中的最大空闲连接 使用负值来表示无限数量的空闲连接
#spring.redis.pool.max-idle= 8
## 连接池中的最小空闲连接 此设置只有在正值时才有效果
#spring.redis.pool.min-idle= 0
## 连接超时（毫秒）
#spring.redis.timeout=30000